# Data preprocessing

## Table of contents

1. [**enc2017 corpus**](#enc2017_corpus)
   1. [Vabamorf's morphological tagging](#vabamorf_morf_tag_1)
   2. [Analysis of the results](#analysis_of_the_results_1)
2. [**Estonian Universal Dependencies' EDT corpus**](#estonian_ud_edt_corpus)
   1. [Extracting the data](#extracting_the_data_2)
   2. [Gathering the data](#gathering_the_data_2)
   3. [Analysis of the results](#analysis_of_the_results_2)
3. [**Homonym disambiguation corpus**](#homonym_disambiguation_corpus)
   1. [Gathering the data](#gathering_the_data_3)

[End](#end)

In [1]:
# Configurations

# Imports
from pathlib import Path

# Paths
DATA_DIR = Path("../data/")
ENC2017_ROOT = DATA_DIR / "enc2017"
UD_ET_EDT_ROOT = DATA_DIR / "ud_et_edt"
HOMONYMS_ROOT = DATA_DIR / "homonymous_word_forms"

ENC2017_DIRS = {
    "processed": ENC2017_ROOT / "processed",
    "raw": ENC2017_ROOT / "raw",
}

UD_ET_EDT_DIRS = {
    "processed": UD_ET_EDT_ROOT / "processed",
    "raw": UD_ET_EDT_ROOT / "raw",
}

HOMONYMS_DIRS = {
    "processed": HOMONYMS_ROOT / "processed",
    "annotations": HOMONYMS_ROOT / "annotations",
}

<a id='enc2017_corpus'></a>

## enc2017 corpus

Data has been gathered from the [corpus](https://github.com/estnltk/eval_experiments_lrec_2020/blob/master/scripts_and_data/enc2017_selection_plain_texts_json.zip) that was used in evaluation experiments reported in LREC 2020 paper "EstNLTK 1.6: Remastered Estonian NLP Pipeline"[^1].

[^1]: Sven Laur, Siim Orasmaa, Dage Särg, Paul Tammo. "EstNLTK 1.6: Remastered Estonian NLP Pipeline". _Proceedings of The 12th Language Resources and Evaluation Conference_. European Language Resources Association: Marseille, France, May 2020, p. 7154-7162

<a id='vabamorf_morf_tag_1'></a>

### Vabamorf's morphological tagging

In [3]:
import os
import sys
import numpy as np
import pandas as pd
import estnltk
import tqdm
import json

# Add the project's root directory to the Python path
sys.path.append(os.path.abspath("../"))

from scripts.preprocessing.enc2017.preprocess import (
    Preprocessor as Enc2017Preprocessor,
)

In [3]:
jsons_dir = ENC2017_DIRS["raw"] / "_plain_texts_json"
jsons = list(jsons_dir.glob("*.json"))

In [4]:
Enc2017Preprocessor.create_json_file_by_file_enc2017(
    jsons=jsons,
    save_dir=ENC2017_DIRS["processed"] / "_vabamorf_morph_texts_json",
    do_morph_layer=True,
    bert_morph_tagger=None,
    necessary_layers=["words", "sentences", "morph_analysis"],
    ignore_errors=False,
    replace_files=False,
)

Beginning to morphologically tag file by file

100%|██████████| 18486/18486 [00:02<00:00, 6677.21it/s]

Morphological tagging completed successfully

In [ ]:
jsons_dir = ENC2017_DIRS["processed"] / "_vabamorf_morph_texts_json"
jsons = list(jsons_dir.glob("*.json"))

In [ ]:
text = estnltk.converters.json_to_text(file=jsons[0])

print("morph_analysis" in text.layers)

True

In [ ]:
text.sentences[0].morph_analysis

Layer(name='morph_analysis', attributes=('normalized_text', 'lemma', 'root', 'root_tokens', 'ending', 'clitic', 'form', 'partofspeech'), spans=SL[Span('Teisipäeval', [{'normalized_text': 'Teisipäeval', 'lemma': 'teisipäev', 'root': 'teisi_päev', 'root_tokens': ['teisi', 'päev'], 'ending': 'l', 'clitic': '', 'form': 'sg ad', 'partofspeech': 'S'}]),
Span('saabus', [{'normalized_text': 'saabus', 'lemma': 'saabuma', 'root': 'saabu', 'root_tokens': ['saabu'], 'ending': 's', 'clitic': '', 'form': 's', 'partofspeech': 'V'}]),
Span('Iisraelist', [{'normalized_text': 'Iisraelist', 'lemma': 'Iisrael', 'root': 'Iisrael', 'root_tokens': ['Iisrael'], 'ending': 'st', 'clitic': '', 'form': 'sg el', 'partofspeech': 'H'}]),
Span('Tallinna', [{'normalized_text': 'Tallinna', 'lemma': 'Tallinn', 'root': 'Tallinn', 'root_tokens': ['Tallinn'], 'ending': '0', 'clitic': '', 'form': 'sg g', 'partofspeech': 'H'}]),
Span('lennujaama', [{'normalized_text': 'lennujaama', 'lemma': 'lennujaam', 'root': 'lennu_jaam', 'root_tokens': ['lennu', 'jaam'], 'ending': '0', 'clitic': '', 'form': 'sg g', 'partofspeech': 'S'}]),
Span('42aastane', [{'normalized_text': '42aastane', 'lemma': '42aastane', 'root': '42_aastane', 'root_tokens': ['42', 'aastane'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'A'}]),
Span('Avraham', [{'normalized_text': 'Avraham', 'lemma': 'Avraham', 'root': 'Avraham', 'root_tokens': ['Avraham'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'H'}]),
Span(',', [{'normalized_text': ',', 'lemma': ',', 'root': ',', 'root_tokens': [','], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}]),
Span('kes', [{'normalized_text': 'kes', 'lemma': 'kes', 'root': 'kes', 'root_tokens': ['kes'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'P'}, {'normalized_text': 'kes', 'lemma': 'kes', 'root': 'kes', 'root_tokens': ['kes'], 'ending': '0', 'clitic': '', 'form': 'pl n', 'partofspeech': 'P'}]),
Span('pidi', [{'normalized_text': 'pidi', 'lemma': 'pidama', 'root': 'pida', 'root_tokens': ['pida'], 'ending': 'i', 'clitic': '', 'form': 's', 'partofspeech': 'V'}]),
Span('hiljem', [{'normalized_text': 'hiljem', 'lemma': 'hiljem', 'root': 'hiljem', 'root_tokens': ['hiljem'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'D'}]),
Span('transiiditsoonist', [{'normalized_text': 'transiiditsoonist', 'lemma': 'transiiditsoon', 'root': 'transiidi_tsoon', 'root_tokens': ['transiidi', 'tsoon'], 'ending': 'st', 'clitic': '', 'form': 'sg el', 'partofspeech': 'S'}]),
Span('väljumata', [{'normalized_text': 'väljumata', 'lemma': 'väljuma', 'root': 'välju', 'root_tokens': ['välju'], 'ending': 'mata', 'clitic': '', 'form': 'mata', 'partofspeech': 'V'}]),
Span('edasi', [{'normalized_text': 'edasi', 'lemma': 'edasi', 'root': 'edasi', 'root_tokens': ['edasi'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'D'}]),
Span('Soome', [{'normalized_text': 'Soome', 'lemma': 'Soome', 'root': 'Soome', 'root_tokens': ['Soome'], 'ending': '0', 'clitic': '', 'form': 'sg g', 'partofspeech': 'H'}]),
Span('lendama', [{'normalized_text': 'lendama', 'lemma': 'lendama', 'root': 'lenda', 'root_tokens': ['lenda'], 'ending': 'ma', 'clitic': '', 'form': 'ma', 'partofspeech': 'V'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}])])

In [ ]:
Enc2017Preprocessor.create_df_enc2017(
    jsons=jsons,
    output_filename=ENC2017_DIRS["processed"] / "enc2017_morph_analysis.parquet",
)

Beginning to create dataset from JSON files.

100%|██████████| 18486/18486 [14:41<00:00, 20.98it/s]

Morphological tagging completed successfully
Tagged texts saved to ..\data\enc2017\processed\enc2017_morph_analysis.parquet

<a id='analysis_of_the_results_1'></a>

### Analysis of the results

In [4]:
pq = pd.read_parquet(ENC2017_DIRS["processed"] / "enc2017_morph_analysis.parquet")

In [ ]:
# Table of pos counts with empty forms ("")
display(pq.groupby("pos")["form"].apply(lambda x: (x == "").sum()))

pos
A      78712
C          0
D     905164
G      19511
H        377
I      10978
J     643654
K     204167
N          0
O          0
P         13
S          0
U          0
V         28
X       2151
Y          0
Z    1830767
Name: form, dtype: int64

In [ ]:
# Examples of empty forms ("") with POS tag "A"
display(pq[(pq["pos"] == "A") & (pq["form"] == "")])

,sentence_id,words,form,pos,type,source
22,1,broneeritud,,A,periodicals,nc_10114_622631.json
27,1,ostetud,,A,periodicals,nc_10114_622631.json
157,0,möödunud,,A,periodicals,nc_10114_622633.json
214,2,kutsunud,,A,periodicals,nc_10114_622633.json
306,1,majajäetud,,A,periodicals,nc_10114_622635.json
...,...,...,...,...,...,...
10389671,12,ettevalmistamata,,A,wikipedia,wiki17_99902_x.json
10389741,15,ebaõnnestunud,,A,wikipedia,wiki17_99902_x.json
10389990,0,glasuurimata,,A,wikipedia,wiki17_99913_x.json
10390014,2,Põletatud,,A,wikipedia,wiki17_99913_x.json
10390164,9,rajatud,,A,wikipedia,wiki17_99953_x.json

In [ ]:
text = estnltk.converters.json_to_text(file=jsons[0])

if "morph_analysis" in text.layers:
    display(text.sentences[1].morph_analysis)

Layer(name='morph_analysis', attributes=('normalized_text', 'lemma', 'root', 'root_tokens', 'ending', 'clitic', 'form', 'partofspeech'), spans=SL[Span('Selleks', [{'normalized_text': 'Selleks', 'lemma': 'see', 'root': 'see', 'root_tokens': ['see'], 'ending': 'ks', 'clitic': '', 'form': 'sg tr', 'partofspeech': 'P'}]),
Span('oli', [{'normalized_text': 'oli', 'lemma': 'olema', 'root': 'ole', 'root_tokens': ['ole'], 'ending': 'i', 'clitic': '', 'form': 's', 'partofspeech': 'V'}]),
Span('tal', [{'normalized_text': 'tal', 'lemma': 'tema', 'root': 'tema', 'root_tokens': ['tema'], 'ending': 'l', 'clitic': '', 'form': 'sg ad', 'partofspeech': 'P'}]),
Span('lennukis', [{'normalized_text': 'lennukis', 'lemma': 'lennuk', 'root': 'lennuk', 'root_tokens': ['lennuk'], 'ending': 's', 'clitic': '', 'form': 'sg in', 'partofspeech': 'S'}]),
Span('koht', [{'normalized_text': 'koht', 'lemma': 'koht', 'root': 'koht', 'root_tokens': ['koht'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}]),
Span('broneeritud', [{'normalized_text': 'broneeritud', 'lemma': 'broneeritud', 'root': 'broneeri=tud', 'root_tokens': ['broneeritud'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'A'}, {'normalized_text': 'broneeritud', 'lemma': 'broneeritud', 'root': 'broneeri=tud', 'root_tokens': ['broneeritud'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'A'}, {'normalized_text': 'broneeritud', 'lemma': 'broneerima', 'root': 'broneeri', 'root_tokens': ['broneeri'], 'ending': 'tud', 'clitic': '', 'form': 'tud', 'partofspeech': 'V'}, {'normalized_text': 'broneeritud', 'lemma': 'broneeritud', 'root': 'broneeri=tud', 'root_tokens': ['broneeritud'], 'ending': 'd', 'clitic': '', 'form': 'pl n', 'partofspeech': 'A'}]),
Span(',', [{'normalized_text': ',', 'lemma': ',', 'root': ',', 'root_tokens': [','], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}]),
Span('kuid', [{'normalized_text': 'kuid', 'lemma': 'kuid', 'root': 'kuid', 'root_tokens': ['kuid'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'J'}]),
Span('piletit', [{'normalized_text': 'piletit', 'lemma': 'pilet', 'root': 'pilet', 'root_tokens': ['pilet'], 'ending': 't', 'clitic': '', 'form': 'sg p', 'partofspeech': 'S'}]),
Span('veel', [{'normalized_text': 'veel', 'lemma': 'veel', 'root': 'veel', 'root_tokens': ['veel'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'D'}]),
Span('ostetud', [{'normalized_text': 'ostetud', 'lemma': 'ostetud', 'root': 'oste=tud', 'root_tokens': ['ostetud'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'A'}, {'normalized_text': 'ostetud', 'lemma': 'ostma', 'root': 'ost', 'root_tokens': ['ost'], 'ending': 'tud', 'clitic': '', 'form': 'tud', 'partofspeech': 'V'}, {'normalized_text': 'ostetud', 'lemma': 'ostetud', 'root': 'oste=tud', 'root_tokens': ['ostetud'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'A'}, {'normalized_text': 'ostetud', 'lemma': 'ostetud', 'root': 'oste=tud', 'root_tokens': ['ostetud'], 'ending': 'd', 'clitic': '', 'form': 'pl n', 'partofspeech': 'A'}]),
Span('polnud', [{'normalized_text': 'polnud', 'lemma': 'olema', 'root': 'ole', 'root_tokens': ['ole'], 'ending': 'nud', 'clitic': '', 'form': 'neg nud', 'partofspeech': 'V'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}])])

<a id='estonian_ud_edt_corpus'></a>

## Estonian Universal Dependencies' EDT [corpus](https://github.com/UniversalDependencies/UD_Estonian-EDT)

<a id='extracting_the_data_2'></a>

### Extracting the data

In [2]:
import os
import sys
import numpy as np
import pandas as pd
import estnltk
import tqdm

# Add the project's root directory to the Python path
sys.path.append(os.path.abspath("../"))

from scripts.preprocessing.ud_et_edt.extract import Extractor as UdEtEdtExtractor
from scripts.preprocessing.ud_et_edt.preprocess import (
    Preprocessor as UdEtEdtPreprocessor,
)

In [3]:
ud_corpus_dir = UD_ET_EDT_DIRS["raw"] / "UD_Estonian-EDT-r2.17"  # UD Corpus location
output_dir = UD_ET_EDT_DIRS["processed"] / "UD_converted"  # Output directory

In [4]:
UdEtEdtExtractor.convert_ud_to_vabamorf(ud_corpus_dir, output_dir, skip_existing=True)

Converting UD corpus to Vabamorf format: 100%|██████████| 3/3 [00:25<00:00,  8.61s/file]
Converting UD morphosyntactic annotations to Vabamorf-like annotations and writing to JSON: 100%|██████████| 43/43 [00:25<00:00,  1.66text/s]

<a id='gathering_the_data_2'></a>

### Gathering the data

In [4]:
jsons_dir = UD_ET_EDT_DIRS["processed"] / "UD_converted"
jsons = list(jsons_dir.glob("*.json"))

In [5]:
UdEtEdtPreprocessor.create_df_ud_corpus(
    jsons=jsons,
    tokenizer="ud_morph_reduced",
    output_filename=UD_ET_EDT_DIRS["processed"] / "ud_edt_morph_analysis.parquet",
)

Beginning to morphologically tag file by file. This can take a while.

Processing files: 100%|██████████| 43/43 [00:41<00:00,  1.04file/s]

Morphological tagging completed successfully
Tagged texts saved to ..\data\ud_et_edt\processed\ud_edt_morph_analysis.parquet

<a id='analysis_of_the_results_2'></a>

### Analysis of the results

In [6]:
pq = pd.read_parquet(UD_ET_EDT_DIRS["processed"] / "ud_edt_morph_analysis.parquet")

In [8]:
# Table of pos counts with empty forms ("")
display(pq.groupby("pos")["form"].apply(lambda x: (x == "").sum()))

pos
''           1
2            0
A         4357
C            1
D        41626
DET          0
DT           1
G          644
H           33
I          319
J        24845
K         9249
N         5890
NN           1
O         1534
P            8
PRP          0
RB           1
S          130
T         1085
U            4
V          194
VBZ          1
X          399
Y         3410
Z        71687
``           1
p            0
place        0
Name: form, dtype: int64

In [ ]:
# Examples of empty forms ("") with POS tag "A"
display(pq[(pq["pos"] == "A") & (pq["form"] == "")])

,sentence_id,words,form,pos,file_prefix,source
5,0,kogu,,A,aja_ee199920,et_edt-ud-dev_000.json
618,37,veendunud,,A,aja_ee199920,et_edt-ud-dev_000.json
769,46,Möödunud,,A,aja_ee199920,et_edt-ud-dev_000.json
873,54,alasti,,A,aja_ee199920,et_edt-ud-dev_000.json
1187,77,kureeritud,,A,aja_ee199920,et_edt-ud-dev_000.json
...,...,...,...,...,...,...
437518,1100,tekitamata,,A,tea_toohoive,et_edt-ud-train_042.json
437547,1102,Kasutatud,,A,tea_toohoive,et_edt-ud-train_042.json
437598,1107,ettenähtud,,A,tea_toohoive,et_edt-ud-train_042.json
437607,1108,valmis,,A,tea_toohoive,et_edt-ud-train_042.json
437691,1114,saanud,,A,tea_toohoive,et_edt-ud-train_042.json

In [11]:
# Examples of empty forms ("") with POS tag "N"
display(pq[(pq["pos"] == "N") & (pq["form"] == "")])

,sentence_id,words,form,pos,file_prefix,source
258,14,1994,,N,aja_ee199920,et_edt-ud-dev_000.json
372,20,18,,N,aja_ee199920,et_edt-ud-dev_000.json
684,41,8,,N,aja_ee199920,et_edt-ud-dev_000.json
685,41,½,,N,aja_ee199920,et_edt-ud-dev_000.json
741,45,8,,N,aja_ee199920,et_edt-ud-dev_000.json
...,...,...,...,...,...,...
437767,1121,1991-2001,,N,tea_toohoive,et_edt-ud-train_042.json
437776,1122,%,,N,tea_toohoive,et_edt-ud-train_042.json
437778,1122,1995-2000,,N,tea_toohoive,et_edt-ud-train_042.json
437785,1123,%,,N,tea_toohoive,et_edt-ud-train_042.json
437787,1123,1995-2000,,N,tea_toohoive,et_edt-ud-train_042.json

In [18]:
text = estnltk.converters.json_to_text(file=jsons[0])

display(text.sentences[0].ud_morph_reduced)

Layer(name='ud_morph_reduced', attributes=('lemma', 'pos', 'form'), spans=SL[Span('Aga', [{'lemma': 'aga', 'pos': 'J', 'form': ''}]),
Span('mulle', [{'lemma': 'mina', 'pos': 'P', 'form': 'sg all'}]),
Span('tundub', [{'lemma': 'tundu', 'pos': 'V', 'form': 'b'}]),
Span(',', [{'lemma': ',', 'pos': 'Z', 'form': ''}]),
Span('et', [{'lemma': 'et', 'pos': 'J', 'form': ''}]),
Span('kogu', [{'lemma': 'kogu', 'pos': 'A', 'form': ''}]),
Span('maailm', [{'lemma': 'maa_ilm', 'pos': 'S', 'form': 'sg n'}]),
Span('ootab', [{'lemma': 'oota', 'pos': 'V', 'form': 'b'}]),
Span('muusikamaailmalt', [{'lemma': 'muusika_maa_ilm', 'pos': 'S', 'form': 'sg abl'}]),
Span('midagi', [{'lemma': 'miski', 'pos': 'P', 'form': 'sg p'}]),
Span('erutavalt', [{'lemma': 'erutavalt', 'pos': 'D', 'form': ''}]),
Span('uut', [{'lemma': 'uus', 'pos': 'A', 'form': 'sg p'}]),
Span('minimalismi', [{'lemma': 'minimalism', 'pos': 'S', 'form': 'sg g'}]),
Span('kõrvale', [{'lemma': 'kõrvale', 'pos': 'K', 'form': ''}]),
Span('.', [{'lemma': '.', 'pos': 'Z', 'form': ''}])])

<a id='homonym_disambiguation_corpus'></a>

## Homonym disambiguation corpus

In [ ]:
import os
import json
import warnings
import types
import pandas as pd
import numpy as np
import estnltk, estnltk.converters, estnltk.taggers
import sklearn

# from bert_morph_tagger_notebook_functions import NotebookFunctions

# from simpletransformers.ner import NERModel, NERArgs
from tqdm import tqdm
from bert_morph_tagger import BertMorphTagger
from estnltk.converters.label_studio.labelling_configurations import (
    PhraseClassificationConfiguration,
)
from estnltk.converters.label_studio.labelling_tasks import PhraseClassificationTask

e:\Git_projects\EstNLTK\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

<a id='gathering_the_data_3'></a>

### Gathering the data

In [ ]:
# Use specific annotation configurations that were used in homonyms dataset
annotation_confs = {
    1: PhraseClassificationConfiguration(
        phrase_labels=["analüüsitav sõna"],
        class_labels={"sg n": "sg n", "sg g": "sg g"},
        header="Vali sõna morfoloogiline vorm (sg n - ainsuse nimetav, sg g -- ainsuse omastav):",
        header_placement="middle",
    ),
    16: PhraseClassificationConfiguration(
        phrase_labels=["analüüsitav sõna"],
        class_labels={"sg n": "sg n", "sg g": "sg g"},
        header="Vali sõna morfoloogiline vorm (sg n - ainsuse nimetav, sg g -- ainsuse omastav):",
        header_placement="middle",
    ),
    17: PhraseClassificationConfiguration(
        phrase_labels=["analüüsitav sõna"],
        class_labels={"sg n": "sg n", "sg g": "sg g", "sg p": "sg p"},
        header="Vali sõna morfoloogiline vorm (sg n - ainsuse nimetav, sg g - ainsuse omastav, sg p - ainsuse osastav):",
        header_placement="middle",
    ),
    19: PhraseClassificationConfiguration(
        phrase_labels=["analüüsitav sõna"],
        class_labels={"sg g": "sg g", "sg p": "sg p", "adt": "adt"},
        header="Vali sõna morfoloogiline vorm (sg g - ainsuse omastav, sg p - ainsuse osastav, adt - lühike sisseütlev):",
        header_placement="middle",
    ),
}

In [ ]:
# Collect input files
input_files = []
input_dir = "./homonymous_word_forms/annotations/"
for fname in os.listdir(input_dir):
    if os.path.isdir(os.path.join(input_dir, fname)):
        for subfname in os.listdir(os.path.join(input_dir, fname)):
            if subfname.endswith(".json"):
                inflection_type = int(subfname.split("_")[2])  # infl_type_xx_1000_vx...
                input_files.append(
                    (
                        inflection_type,
                        "./homonymous_word_forms/annotations/" + fname + "/" + subfname,
                    )
                )

if not input_files:
    raise RuntimeError("No input files found!")

print(f"Found {len(input_files)} input files.")

Found 8 input files.

In [ ]:
overall_data = []
# Extract data from input files
for infl_type, input_file in input_files:
    print(f"Processing file: {input_file} (inflection type {infl_type})")
    num = input_file.split("/")[3]
    annotation_conf = annotation_confs[infl_type]
    with open(input_file, "r", encoding="utf-8") as f:
        raw = f.read()
    task = PhraseClassificationTask(
        annotation_conf,
        input_layer="morph",
        output_layer="morph",
        label_attribute="label",
    )
    classified_sentences = task.import_data(raw)

    # Create dataframe from classified sentences
    data = []
    for sentence in classified_sentences:
        for annotation in sentence.morph:
            if (
                "class_label" in sentence.meta
                and sentence.meta["class_label"] is not None
            ):
                data.append(
                    {
                        "num": num,
                        "inflection_type": infl_type,
                        "sentence": sentence.text,
                        "word": annotation.text,
                        "word_span": (annotation.start, annotation.end),
                        "label": sentence.meta["class_label"],
                    }
                )
    df = pd.DataFrame(data)
    output_csv = (
        f"./homonymous_word_forms/processed/homonyms_infltype_{num}_{infl_type}.csv"
    )
    df.to_csv(output_csv, index=False)
    print(f"Saved processed data to {output_csv}")
    overall_data.extend(data)

# Create overall dataframe
overall_df = pd.DataFrame(overall_data)
overall_output_csv = "./homonymous_word_forms/processed/homonyms_overall.csv"
overall_df.to_csv(overall_output_csv, index=False)
print(f"Saved overall processed data to {overall_output_csv}")

Processing file: ./homonymous_word_forms/annotations/1/infl_type_01_1000_v1_project-1-at-2024-11-23-00-10-742338cd.json (inflection type 1)
Saved processed data to ./homonymous_word_forms/processed/homonyms_infltype_1_1.csv
Processing file: ./homonymous_word_forms/annotations/1/infl_type_16_1000_v1_project-2-at-2024-11-21-19-27-9e8ae0c2.json (inflection type 16)
Saved processed data to ./homonymous_word_forms/processed/homonyms_infltype_1_16.csv
Processing file: ./homonymous_word_forms/annotations/1/infl_type_17_1000_v1.json (inflection type 17)
Saved processed data to ./homonymous_word_forms/processed/homonyms_infltype_1_17.csv
Processing file: ./homonymous_word_forms/annotations/1/infl_type_19_1000_v1_project-6-at-2025-11-15-14-13-42753676.json (inflection type 19)
Saved processed data to ./homonymous_word_forms/processed/homonyms_infltype_1_19.csv
Processing file: ./homonymous_word_forms/annotations/2/infl_type_01_1000_v2_project-5-at-2024-12-11-21-53-280753b4.json (inflection type 1)
Saved processed data to ./homonymous_word_forms/processed/homonyms_infltype_2_1.csv
Processing file: ./homonymous_word_forms/annotations/2/infl_type_16_1000_v2_project-5-at-2025-01-03-01-42-87bca577.json (inflection type 16)
Saved processed data to ./homonymous_word_forms/processed/homonyms_infltype_2_16.csv
Processing file: ./homonymous_word_forms/annotations/2/infl_type_17_1000_v2.json (inflection type 17)
Saved processed data to ./homonymous_word_forms/processed/homonyms_infltype_2_17.csv
Processing file: ./homonymous_word_forms/annotations/2/infl_type_19_1000_v2_project-7-at-2025-11-21-23-02-24f590e4.json (inflection type 19)
Saved processed data to ./homonymous_word_forms/processed/homonyms_infltype_2_19.csv
Saved overall processed data to ./homonymous_word_forms/processed/homonyms_overall.csv

<a id='end'></a>

### END