In [1]:
# Example: reading full text
import os, os.path

from estnltk import Text
from estnltk.converters import json_to_text

in_dir = '_plain_texts_json'

text = json_to_text(file=os.path.join(in_dir, 'nc_1014_85632.json'))
text

Text(text='Odaviskaja Moonika Aava püstitas kergejõustiku Eesti GP sarja avaetapil Tartus Eesti rekordi 57.27. Gerd Kanter heitis ketast 59.13 ja Ivo Kala 57.27.\n\nRekord sündis juba avakatsel . " Soovisin kohe tulemuse ära visata . Kartsin , et hiljem muutub selg valusaks , " rääkis Aava . " Tehniliselt oli vise nigel . Kui oda käest lahti läks , arvasin , et lendab 55 meetri kanti . "\n\nUueks sihiks seab Aava 59 m viske , mis tagaks pääsu Edmontoni MMile . " Usun , et see on reaalne , tänane tulemus lisas kindlust , " kinnitas ta .\n\nAava ja Šikolenko 100dollariline kihlvedu\n\nJuba 1996. aastal vana tüüpi odaga 55.79 visanud Aava vaevles aastaid vigastuste küüsis . Esmalt tegi häda küünarvars , seejärel muutus valulikuks selg . Vaatamata sellele uskus Aava , et suudab veel kunagi kaugele visata . " Odavise on ala , mida oskan - arvan , et seda oskust tuleb veelgi arendada , " mõtiskles ta . " Tänavusest hooajast olen harjutanud professionaalsel tasemel . "\n\nKevadel viibis Aava Hispaanias treeningulaagris koos Venemaa kuulsuse Tatjana Šikolenko ja leedulanna Rita Ramanuskaitega . " Ritaga sõlmisime saja dollari peale kihlveo , kas mina viskan enne 59 või tema 66 meetrit , " tunnistas Aava . " Mina seda summat igatahes kaotada ei kavatse . "\n\nKõhuhäda röövis Gerd Kanterilt kilo\n\nTibutavas vihmas alanud kettaheites püstitas Kanter juba avakatsel isikliku rekordi 57.98. Teisel üritusel maandus ketas veelgi kaugemal - 59.13. Tihedat konkurentsi pakkunud Ivo Kala vastas samal ajal 56.04 ja 57.27. " Hea , kui keegi teeb kodus seljataguse tuliseks , " hindas Kanter .\n\nHiljem ei suutnud kumbki tulemust parandada . Viiendal katsel võttis Kanter sihilkule  kaameramehe , tabades hinnalise aparaadi statiivi .\n\n" Kerge vihm tegi rõõmu , " väitis Kanter . " Krobeline heitering muutus parajalt libedaks . " Noor kettamees ei pidanud rekordkatselt tehniliselt kuigi heaks . " Kõik heited kaldusid sektori serva , " analüüsis ta . " Kettaheitja tulemus algab 60-meetrist . "\n\nVõistluse eel ei osanud Kanter rekordiparandust oodata . " Viimased kaks päeva maadlesin kõhuhädaga . Öösel ei saanud korralikult magada , kaotasin kehakaalust ühe kilo , " kirjeldas ta läbielamisi . " Lisaks mõlkusid mõtted homse diplomitöö kaitsmise juures . "\n\nTaas tehnikaga kimpus olnud odaviskaja Andrus Värnik püstitas hooaja margi 74.92. Taktikakavaldamise käigus jäi kõrgushüppe favoriit Marko Aleksejev alla Andrei Marhelile , tulemused 2.13 ja 2.10.\n\nKolmikhüppes võidutses 16.07ga Ilja Tumorin . " Jõudu ja kiirust on palju , ent tehnika jätab soovida , " sõnas ta . " Hoojooks on tõsine probleem , pean selle kallal tugevalt töötama . "\n\nNoor ema Käärt võimsalt tagasi\n\nNaiste 100 m jooksu võitnud Katrin Käärt peitis pärast finišit näo kätesse ja poetas rõõmupisara . Aeg 12,09 tähendas 10. novembril tütar Karoli sünnitanud 17aastasele neiule isiklikku rekordit .\n\n" Tagasitulek polnud lihtne . Kolm nädalat pärast sünnitust hakkasin sörkima , tõsisemaid treeninguid alustasin aprillis , " rääkis Käärt . " Esimesel võistlusel ei osanud nii head aega oodata . "\n\nMeeste 100 m jooksu võitnud Katrini elukaaslase Garol Pärna hinnangul muutis sünnitus Katrini tugevamaks . " Ta peab pingutustele paremini vastu , " kiitis Pärn . Katrin nõustus : " Organism on tõesti tugevnenud , treeningutel jooksen varasemast pikemaid lõike . "\n\nEma ja isa treeningute ajal magab väike Karoli staadionil lapsevankris . " Aitäh emale , kes vajadusel lapsega jalutab , " sõnas Käärt . " Elurütmi Karoli ei häiri . Läheme kell kaheksa koos magama ning ärkame hommikul kell kuus . "')